apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ido123ziv/gitops-cert-level-2-examples.git"
    targetRevision: HEAD
    path: environment-promotion/envs/staging
  destination:
    server: "https://kubernetes.default.svc"
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
